apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-claim
  labels:
    app: henexdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default